name: deploy-docker-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY_IMAGE: 0x-jerry/pumpkin

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  docker-build-deploy:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            platforms: linux/arm64
          - os: ubuntu-latest
            platforms: linux/amd64

    runs-on: ${{matrix.os}}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check Repository
        id: repo_check
        run: |
          if [ "${{ github.repository }}" != "Pumpkin-MC/Pumpkin" ]; then
            echo "Not the target repository. Skipping deployment."
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "Target repository confirmed. Proceeding with deployment."
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        if: steps.repo_check.outputs.should_deploy == 'true'
        uses: actions/checkout@v6

      - name: Login to GitHub CR
        if: steps.repo_check.outputs.should_deploy == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Versions
        if: steps.repo_check.outputs.should_deploy == 'true'
        id: versions
        run: |
          VERSION=$(awk -F '"' '/^version/ {print $2}' Cargo.toml)
          echo "PUMPKIN_VERSION=$(echo $VERSION | cut -d '+' -f 1)" >> $GITHUB_ENV
          echo "MC_VERSION=$(echo $VERSION | cut -d '+' -f 2)" >> $GITHUB_ENV

      - name: Extract Metadata
        if: steps.repo_check.outputs.should_deploy == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=sha
            type=raw,value=mc${{ env.MC_VERSION }}
            type=raw,value=${{ env.PUMPKIN_VERSION }}
            type=raw,value=mc${{ env.MC_VERSION }}-${{ env.PUMPKIN_VERSION }}

      - name: Docker Buildx
        if: steps.repo_check.outputs.should_deploy == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: build
        if: steps.repo_check.outputs.should_deploy == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platforms }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export Digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload Digest
        uses: actions/upload-artifact@v6
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - docker-build-deploy
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v7
        with:
          name: digests
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=sha
            type=raw,value=mc${{ env.MC_VERSION }}
            type=raw,value=${{ env.PUMPKIN_VERSION }}
            type=raw,value=mc${{ env.MC_VERSION }}-${{ env.PUMPKIN_VERSION }}

      - name: Login to GitHub CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Manifest and Push Image
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
            
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}